spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: product_ms
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
