spring:
  application:
    name: product-service
  profiles:
    active: development
  config:
    import: configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: product_ms
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      profile: development
      fail-fast: true
      retry:
        max-attempts: 5
        max-interval: 3000
        initial-interval: 1500

server:
  port: 8082

logging:
  level:
    org.springframework: DEBUG
