spring:
  application:
    name: product-service
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: product_ms
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      enabled: false

server:
  port: 8082

logging:
  level:
    org.springframework: DEBUG
